taglib/taglib

taglib/CMakeLists.txt

uncompr.c is no longer used since caa53e8

Remove an unused file from taglib/CMakeLists.txt.

---

taglib/riff/aiff/aifffile.cpp
tests/test_aiff.cpp

```hasID3v2Tag()``` is in the header file but doesn't exist in the source file.
This is part of #488, but I decided to create a separate pull request since this is a fatal error and should be fixed immediately.

Implement missing AIFF::File::hasID3v2Tag().

---

taglib/riff/wav/wavfile.cpp
tests/test_wav.cpp

The old tag won't be removed when the new tag is empty.
This fixes #500.

Fix saving ID3v2/INFO tags of WAV files.

---

taglib/asf/asffile.cpp

This (looks like) fixes #524.
After playing with WMP for some time, I got an idea that some GUID fields like ```WM/MediaClassPrimaryID```, ```WM/WMCollectionID```... should belong to MetadataLibraryObject. It looks like the bug has been fixed, but I'm not sure this solution is robust enough.
Any thoughts?

Fix saving WMA files with some GUID fields.

---

taglib/toolkit/tbytevector.cpp
tests/test_bytevector.cpp

This fixes #529.
It's a subtle bug of ```ByteVector``` and it have to be attributed to me. ```ByteVector::begin()``` and related functions return wrong iterator in some cases. For example, after doing like this:
```
// line 247 of oggpage.cpp
packetBuf = packetBuf.mid(SPLITSIZE);
```
Sorry for causing such a bug and thank you for cathing it.

Fix ByteVector to return correct iterators after detached.

---

tests/test_bytevector.cpp

The test I added at #531 lacks ```end()```, ```rbegin()``` and ```rend()```.

A little robuster tests for ByteVector iterators after detaching.

---

taglib/toolkit/tbytevector.cpp
tests/test_bytevector.cpp

The expanded area will be filled with garbage instead of correct padding in some corner cases.
Related to #531, I found another corner case bug of ```ByteVector```. It won't affect badly as far as I tested, but bug is bug.

Fix the wrong padding of ByteVector::resize().

---

taglib/mpeg/id3v2/frames/chapterframe.cpp
taglib/mpeg/id3v2/frames/synchronizedlyricsframe.cpp

Replace use of bytevector.mid(pos,4).toUInt() with more optimized bytevector.toUInt(pos)

 bytevector.mid(pos,4).toUInt() => bytevector.toUInt(pos)

---

taglib/mpeg/id3v2/id3v2tag.cpp

FreeBSD-8.2 (GCC 4.2.1) errors with uint ambiguity ...

Silenced uint ambiguity error.

---

taglib/mpeg/id3v2/id3v2frame.cpp
taglib/mpeg/id3v2/id3v2tag.cpp
tests/test_id3v2.cpp

Skip empty ID3v2 frames when saving an ID3v2 tag.

---

taglib/mpeg/id3v2/id3v2tag.cpp

No need to call ID3v2::Frame::render() twice when saving an ID3v2 tag.

---

tests/utils.h

Unfortunately, MSVC doesn't have ```snprintf``` and ```tempnam``` is deprecated on Windows too.
This should work with either MSVC or MinGW.

Modify the test code to work on MSVC/Windows.

---

tests/utils.h

const char * is more preferable than string for ifstream constructor.
The overload takes a string was newly introduced since C++11.

Fix test code to work on some environments.

---

taglib/toolkit/tfile.cpp
tests/CMakeLists.txt
tests/test_file.cpp

Fix File::rfind() for small files.

---

taglib/toolkit/tmap.tcc

http://www.cplusplus.com/reference/map/map/erase/

std::map::erase() can take a key directly and has no-throw guarantee.

---

taglib/riff/aiff/aifffile.cpp
taglib/riff/wav/wavfile.cpp

Similar to #492.
There is no good reason to use the last chunk rather than the first one.

Skip duplicate chunks when reading AIFF/WAV files.

---

taglib/toolkit/tstring.cpp

Use wmemcpy() rather than memcpy() and sizeof(wchar_t).

---

taglib/ape/apefile.h
taglib/flac/flacfile.h
taglib/mpc/mpcfile.cpp
taglib/mpc/mpcfile.h
taglib/trueaudio/trueaudiofile.h
taglib/wavpack/wavpackfile.h

Just a small refactoring. Removing private functions doesn't affect the ABI compatibility.

Remove some unused private function prototypes.

---

taglib/toolkit/tfile.cpp
taglib/toolkit/tfilestream.cpp

Mismatched buffer size between ```File``` and ```FileStream``` sometimes may cause useless memory reallocation.
Additionally, I realized that different buffer size between Linux and Windows doesn't help improve the performance.

Fix mismatched file I/O buffer sizes.

---

CMakeLists.txt

This is in response to #613. ```pkg-config``` works on Windows too.

Enable pkg-config on Windows.

---

taglib/mpc/mpcfile.cpp

Just a small refactoring. That's definitely useless since ```MPC::File::findAPE()``` doesn't touch any internal data members.

Remove an useless function call.

---

taglib/toolkit/tbytevector.h

Related to #615. Add a comment that ```ByteVector::checksum()``` is not generic.

(minor, comment only) Add a supplementary comment to ByteVector::checksum().

---

tests/utils.h

Just casts the return value of ```mkstemps()``` to ```void```.

Silence a GCC warning about ignoring a return value in test.

---

taglib/mp4/mp4file.cpp
taglib/mp4/mp4file.h
taglib/mp4/mp4properties.cpp
taglib/mp4/mp4properties.h
tests/test_mp4.cpp

Move parsing code to read() for consistency with other classes.

(wishlist) MP4: AudioProperties improvements

---

taglib/mpc/mpcfile.cpp
taglib/mpc/mpcfile.h
taglib/mpc/mpcproperties.cpp
taglib/mpc/mpcproperties.h
tests/test_mpc.cpp

Remove some data members which are not needed to carry.

(wishlist) MusePak: AudioProperties improvements

---

taglib/ogg/opus/opusfile.cpp
taglib/ogg/opus/opusfile.h
taglib/ogg/opus/opusproperties.cpp
taglib/ogg/opus/opusproperties.h
tests/test_opus.cpp

Remove some data members which are not needed to carry.

(wishlist) Ogg Opus: AudioProperties improvements

---

taglib/ogg/speex/speexfile.cpp
taglib/ogg/speex/speexfile.h
taglib/ogg/speex/speexproperties.cpp
taglib/ogg/speex/speexproperties.h
tests/CMakeLists.txt
tests/test_speex.cpp

Add bitrateNominal() property.
Remove some data members which are not needed to carry.

(wishlist) Ogg Speex: AudioProperties improvements

---

taglib/ogg/vorbis/vorbisfile.cpp
taglib/ogg/vorbis/vorbisfile.h
taglib/ogg/vorbis/vorbisproperties.cpp
taglib/ogg/vorbis/vorbisproperties.h
tests/test_ogg.cpp

Remove some data members which are not needed to carry.

(wishlist) Ogg Vorbis: AudioProperties improvements

---

taglib/riff/aiff/aifffile.cpp
taglib/riff/aiff/aifffile.h
taglib/riff/aiff/aiffproperties.cpp
taglib/riff/aiff/aiffproperties.h
tests/test_aiff.cpp

Add bitsPerSample() property besides sampleWidth(). (#360)

(wishlist) AIFF: AudioProperties improvements

---

taglib/wavpack/wavpackproperties.cpp

FreeBSD fails to build with uint ambiguity error.

Silence uint ambiguity error in wavepackproperties.

---

ConfigureChecks.cmake
config.h.cmake
taglib/toolkit/tutils.h

I become aware of the fact that some systems lacks ```vsnprintf``` despite that they have ```snprintf```.
So I'd like to change the CMake tests to check ```vsnprintf``` directly rather than ```snprintf```.

CMake check for vsprintf_s/vsnprintf rather than sprintf_s/snprintf.

---

CMakeLists.txt

While using this library as Subproject there could be conflicts with 'uninstall' target with other libs. Cmake error like this:
```CMake Error at libraryY/CMakeLists.txt:63 (add_custom_target):
add_custom_target cannot create target "doc" because another target with
the same name already exists.  The existing target is a custom target
created in source directory
"/path/to/libraryX".  See
documentation for policy CMP0002 for more details.```
And current support of CMP0002 policy is buggy on stable cmake package.

Install target should be checked to avoid conflicts

---

taglib/toolkit/tfilestream.cpp
tests/test_file.cpp

Not an urgent bug. It will affect in so unlikely cases that actually do no harm. For example, seeking an ID3v1 tag in a file smaller than 128 bytes.

Fix inconsistent negative seek behavior between Linux and Windows.

---

taglib/mpeg/mpegfile.cpp

Related to #577. I missed out on the fact that we can also skip an APE tag.

Skip both ID3v1 and APE tags when seeking the last MPEG frame.

---

taglib/mp4/mp4tag.cpp
tests/test_mp4.cpp

Fixes #670
- Fixes access violation when setting empty stringlist on integer
properties in mp4 tag
- Add a unit test that validates the fix.

Fixes access violation

---

taglib/mp4/mp4file.cpp
taglib/mp4/mp4file.h
tests/test_mp4.cpp

We can check if an MP4 file on disk actually has a tag. I was totally wrong in #252. Sorry @joelverhagen!

Add a method to check if an MP4 file on disk actually has a tag.

---

taglib/ape/apetag.cpp

The workaround for the old Solaris Studio compiler causes compilation errors on the newer version

check SUNPRO_CC version before using Map workaround

---

taglib/toolkit/tbytevector.cpp

The Solaris Studio 12.4 compiler chokes on const conversion for ByteVector::rbegin() and ByteVector::rend() with the following errors:
"taglib/toolkit/tbytevector.cpp", line 749: Error: Cannot return std::reverse_iterator<char*, std::random_access_iterator_tag, char, char&, char*, int> from a function that should return std::reverse_iterator<const char*, std::random_access_iterator_tag, char, const char&, const char*, int>.
"taglib/toolkit/tbytevector.cpp", line 760: Error: Cannot return std::reverse_iterator<char*, std::random_access_iterator_tag, char, char&, char*, int> from a function that should return std::reverse_iterator<const char*, std::random_access_iterator_tag, char, const char&, const char*, int>.
The following patch corrects the constness of the reverse iterators to help …

return const correct reverse iterator for newer Sun compiler

---

taglib/CMakeLists.txt
taglib/mpeg/id3v2/frames/podcastframe.cpp
taglib/mpeg/id3v2/frames/podcastframe.h
taglib/mpeg/id3v2/id3v2frame.cpp
taglib/mpeg/id3v2/id3v2framefactory.cpp

I would like to bring up again the case of the proprietary Apple podcast frames because I have received a [feature request](http://sourceforge.net/p/kid3/feature-requests/60/).
Three years ago, Hasso Tepper created a fork for the WFED (a strange hybrid being a text information frame with the name of a URL link frame) and some less suspicious text information frames. He announced it on the [mailing list](https://mail.kde.org/pipermail/taglib-devel/2012-September/002335.html), but maybe missed to create a pull request for his [apple-frames branch](https://github.com/hasso/taglib/commit/bdf06fb335759576521b816cceb6ddefa07c08ed).
I have taken his branch and put an implementation of the PCST frame (another strange creation being a frame which has just four zero bytes and its existence marks …

Support for Apple podcast frames

---

taglib/toolkit/tbytevector.cpp
taglib/toolkit/tbytevector.h
tests/test_bytevector.cpp

Especially remove the useless nested RefCounters.
I implemented the copy-on-write operation of ```ByteVector::mid()``` almost two years ago to fix #121 or to speed up parsing some huge tags, and I think it was successful. However, its implementation was overly complicated due to my hastiness and poor coding skill. (especially, it has nested ```RefCounter```s) I have been concerned with it for a long time.
Even though this is focused on simplifying the code, not improving the performance, it makes the ```mid()``` operations slightly faster.

Simplify overly complicated ByteVector::mid() implementation.

---

taglib/mpeg/id3v2/id3v2tag.cpp
taglib/mpeg/mpegfile.cpp
taglib/mpeg/mpegfile.h
tests/test_id3v2.cpp

(same as #616, sorry for re-creating this one.)
This moves the code I added at #454 from ```MPEG::File``` to ```MPEG::ID3v2::Tag``` because of these points:
* Enable other File classes to treat duplicate ID3v2 tags properly.
* Enable ```MPEG::ID3v2::Tag``` to erase duplicate tags.
Additionally, it will help me fix some of the bugs I reported in #606.

Skip duplicate ID3v2 tags and treat them as an extra blank of the first one.

---

taglib/ape/apefile.cpp
taglib/flac/flacfile.cpp
taglib/mpc/mpcfile.cpp
taglib/mpeg/mpegfile.cpp
taglib/riff/wav/wavfile.cpp
taglib/riff/wav/wavfile.h
taglib/tagunion.cpp
taglib/tagunion.h
taglib/trueaudio/trueaudiofile.cpp
taglib/wavpack/wavpackfile.cpp
tests/test_ape.cpp
tests/test_mpc.cpp
tests/test_mpeg.cpp
tests/test_trueaudio.cpp
tests/test_wav.cpp
tests/test_wavpack.cpp

This fixes #626 by backporting ```TagUnion::properties()``` and ```TagUnion::removeUnsupportedProperties()``` from taglib2 with one of those ugly workarounds to emulate virtual functions.
This PR is too large to review soon. So I have no intention to merge it into v1.10 beta.

Fix segfaults when calling File::properties() after strip().

---

NEWS
taglib/asf/asffile.cpp
taglib/asf/asffile.h
tests/test_asf.cpp

This fix #621.
I reported several similar bugs, but this one is relatively easy to fix. I think we can merge it to v1.10.
The points of this fix are:
* Clear all ```attributeData```s before adding things to them.
* Update ```d->headerSize``` after writing a tag.
This also reduces memory reallocations and copies when saving ASF files.

Avoid writing duplicate tags when saving ASF files.

---

taglib/fileref.cpp
taglib/fileref.h
tests/test_fileref.cpp

Refs issue #526 
I haven't tested it on WinRT (which is the main reason for this, but it works fine on linux)
I'm submitting this for early review and will post the WinRT results as soon as I have a build & it's integrated.
Cheers,

FileRef: Allow an IOStream to be used

---

CMakeLists.txt

Instead of having the version information both in CMakeLists.txt and
taglib/toolkit/taglib.h, it is now generated from CMake into a header file.

Avoid duplicate version information.

---

taglib/toolkit/tstring.cpp
taglib/toolkit/tstring.h
tests/test_string.cpp

Some functions and a variable in ```tstring.h``` are not needed to be exposed in a public header.
Basically the same idea as fbd3b71690cedd70b9175d55a1e089aaca748046, but hides more things.

Hide private things from a public header.

---

CMakeLists.txt

ccache is a compiler cache. It speeds up recompilation by caching previous compilations and detecting when the same compilation is being done again. It provides support for C/C++ languages.
It makes compilation fast if it is available on the machine.
https://ccache.samba.org/

Added ccache support for faster compilation

---

taglib/fileref.cpp

In VLC we use taglib a lot to get title/author/etc of audio and video files. M4V is among the common file formats that taglib can parse easily.

Add support for M4V tag parsing

---

taglib.pc.cmake

as title says. libdir / includedir shall never be hardcoded in generated pkgconfig file.

fix pkgconfig file for cross compiling

---

CMakeLists.txt
INSTALL
examples/CMakeLists.txt

Hi all,
This patch makes taglib more standard wrt CMake options, so makes easier its integration in distros.
Regards,
Samuel

cmake: improve distro integration allowing to use the standard CMake options

---

taglib/flac/flacfile.cpp
tests/test_flac.cpp

This is basically the same as #586 which has already been reviewed.

Remove duplicate Vorbis comment blocks when saving a FLAC file.

---

taglib/flac/flacfile.cpp
taglib/flac/flacfile.h
tests/test_flac.cpp

This is related to #646. 
This adds a method named ```strip()``` to ```FLAC::File```. It works like other ```strip()``` methods, but it preserves the vendor ID instead of removing the Vorbis comment block completely.

Enable FLAC::File to remove non-standard tags.

---

taglib/mpeg/id3v2/id3v2tag.cpp
tests/test_id3v2.cpp

iTunes writes the 2.4 frames TSOA, TSOT, TSOP to 2.3 files.  (It
additionally defines TSO2 and TSOC for both 2.3 and 2.4.)  TagLib should
not delete these frames.

Handle iTunes ID3v2.3 hacks

---

CMakeLists.txt

This change originated from porting this library to [Haiku OS](https://www.haiku-os.org/). There has also been a post on the mailing list regarding this patch. All it does is allow the user to overwrite the installation directories for the different components of taglib, which is useful, when working with a different general folder structure than the one found on Linux. This change does not break any existing build process, it only enables the user to overwrite the directories if they so desire.

Remove "FORCE" in CMake path specifications to allow installation to a non-standard directory structure

---

taglib/ogg/oggfile.cpp
taglib/ogg/oggfile.h
taglib/ogg/oggpage.cpp
taglib/ogg/oggpage.h
taglib/ogg/oggpageheader.cpp
taglib/ogg/oggpageheader.h

This also reduces memory usage when reading/writing Ogg files.
Especially, it stops holding an entire file when renumbering Ogg pages.
This PR fixes the bug reported at #620. But it finally came to a huge refactoring and will require a thorough review.

Fix a segfault when saving an Ogg file repeatedly.

---

taglib/CMakeLists.txt
taglib/toolkit/taglib.cpp
taglib/toolkit/taglib.h

The current way of exposing TagLib's version only through #define's
makes it impossible for clients (e.g. language bindings) to reliably
determine the TagLib version that is currently in use: using the
define's in client code will statically copy the compile-time values
into the client's library, but if TagLib is dynamically bound the
version (at least minor and patch version) can change after building
client code.

Adds a function for dynamic version information retrieval

---

CMakeLists.txt

`cmake_minimum_required()` command must be at the beginning of the top-level CMakeLists.txt file even before calling the `project()` command, [proof](https://cmake.org/cmake/help/v3.3/command/cmake_minimum_required.html).

Move cmake_minimum_required at the top

---

taglib/toolkit/tbytevectorstream.cpp
tests/test_bytevectorstream.cpp

This fixes the problem described in my e-mail to the development list ("Possible bug in MPEG::File::strip"). The bug in ByteVectorStream::seek() caused MPEG::File to not detect any present ID3v1 tag whenever it was using a ByteVectorStream as input. So strip() wasn't even aware of the tag's existence.

Fix defect in ByteVectorStream::seek when Position==End.

---

taglib/mp4/mp4tag.cpp
taglib/mpeg/id3v2/id3v2frame.cpp
taglib/mpeg/id3v2/id3v2framefactory.cpp
tests/test_id3v2.cpp
tests/test_mp4.cpp

M4A:
©wrk: Work (string)
©mvn: Movement Name (string)
©mvi: Movement Number (number)
©mvc: Movement Count (number)
shwm: Show Work & Movement (0/1)
ID3 (2.3, 2.4; MVN, MVI for 2.2):
MVNM: Movement Name
MVIN: Movement Number/Count

Support new classical music frames introduced with iTunes 12.5, #758.

---

taglib/toolkit/tstring.cpp
tests/test_string.cpp

Optimize `String::substr` when returning itself as a substring (i.e. returning whole string).
Use copy ctor to return in a case whole string is being returned.
The intention was to optimize `String::stripWhiteSpace` for no-strip case (without any leading or trailing white space removal).
`copyFromUTF16` was used in any case previously and allocated duplicate buffer for the same string - no implicit sharing.

String::substr optimization

---

taglib/flac/flacfile.cpp

IMHO this fix is okay but I'd like someone with better understanding of the `FLAC::File` internals to review it before merging.
Thanks,
Michael

Fixes #743 by not overwriting existing Xiph comment in FLAC::File::save

---

taglib/mp4/mp4item.cpp
taglib/mp4/mp4tag.cpp

Fixed errors occurring when saving pictures to mp4 containers when taglib is compiled to use wstrings.

Fixed incorrect handling of MP4 tags when using wstrings

---

taglib/mp4/mp4tag.cpp

Although the rate atom is technically unnofficial, it is widely supported with the standard form of using integers 0-100 and dividing by 20 to get a 5 star rating. Previously attempts to write this tag would fail by trying to treat this atom as general text. This treats the atom as an integer during both reading and writing.
Resolves #817

Add direct support for "rate" atom

---

CMakeLists.txt
ConfigureChecks.cmake
taglib/toolkit/tfilestream.cpp

Don't rely on `_WIN32_WINNT` value to enable WinRT support.
if _WIN32_WINNT is not set manually, it is defaulted to SDK version. So if you use SDK > 8 you cannot use TagLib under Win7 and lower because of `CreateFile2` function dependency.
`PLATFORM_WINRT` option (`OFF` by default) was introduced to enable WinRT build.
Related issues: https://github.com/Microsoft/vcpkg/issues/1240

Fix WinRT configuring

---

tests/test_synchdata.cpp

powerpc is a platform with 'char' == 'unsigned char'.
As a result '-1' is not expressible in char and build fails as:
```
$ cmake .. -DBUILD_TESTS=YES -DCMAKE_CXX_FLAGS="-O2 -funsigned-char" -DCMAKE_C_FLAGS="-O2 -funsigned-char"
...
$ make check
tests/test_synchdata.cpp: In member function 'void TestID3v2SynchData::testToUIntBroken()':
tests/test_synchdata.cpp:78:33: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
char data[] = { 0, 0, 0, -1 };
^
```
The fix is to expliticly cast -1 to 'char'.
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>

taglib: fix test build failure on powerpc/c++11

---

taglib/mpeg/id3v2/id3v2framefactory.cpp

If TDRC is encrypted, FrameFactory::createFrame() returns UnknownFrame
which causes problems in rebuildAggregateFrames() when it is assumed
that TDRC is a TextIdentificationFrame
Fixes #829

Don't assume TDRC is an instance of TextIdentificationFrame

---

taglib/mpeg/mpegfile.cpp

This is not really  a question. When loading an empty (empty.txt -> empty.mp3 ), program will crash.
buffer.size() is 0, then buffer.size() - 1 is undefined (unsigned int).

Crash when loading an empty mpeg file

---

taglib/tagunion.cpp
taglib/tagunion.h

Added setProperties implementation to TagUnion.
It works by calling setProperties  on each tag making up the union and returns only the properties unsupported by all member tags as unsupported.
This allows many commonly supported properties that are not part of the base Tag class accessors (AlbumArtist for example) to be read and written.

Added setProperties implementation to TagUnion

---

taglib/ogg/flac/oggflacfile.cpp

Took a stab at fixing CVE-2018-11439 and (#868). Would appreciate an experience taglib developer reviewing this. First time looking at the FLAC - ogg mapping and working on taglib here, so I might have incorrectly interpreted the header or other taglib conventions.

Fixed OOB read when loading invalid ogg flac file. (#868)

---

taglib/mpeg/id3v2/frames/textidentificationframe.cpp

Before:
```
$ ./examples/framelist ../tests/data/rare_frames.mp3 
******************** "../tests/data/rare_frames.mp3"********************
ID3v2.4.0, 997 bytes in tag
COMM - "A COMMENT"
TXXX - "[userTextDescription1] userTextDescription1 userTextData1 userTextData2"
TXXX - "[QuodLibet::userTextDescription2] QuodLibet::userTextDescription2 userTextData1 userTextData2"
TCON - "13"
WXXX - "[userUrl] http://a.user.url"
WXXX - "[] http://a.user.url/with/empty/description"
```
After:
```
$ ./examples/framelist ../tests/data/rare_frames.mp3 
******************** "../tests/data/rare_frames.mp3"********************
ID3v2.4.0, 997 bytes in tag
COMM - "A COMMENT"
TXXX - "[userTextDescription1] userTextData1 userTextData2"
TXXX - "[QuodLibet::userTextDescription2] userTextData1 userTextData2"
TCON - …
```

Don't list the description twice in `UserTextIdentificationFrame::toString()`

---

taglib/mp4/mp4properties.cpp

The 'unit' (timescale) of 'mdhd' v1 atoms is a 32-bit unsigned integer (4 bytes long), but is parsed as a 64-bit integer (8 bytes long). This also affects the byte offset of the 'length' (duration).  This results in MP4 AudioProperties reporting a track length of zero.
This change addresses both problems.
Resolves #891
See:
https://wiki.multimedia.cx/index.php/QuickTime_container

Fixed an MP4 AudioProperties parsing error

---

taglib/mp4/mp4properties.cpp

Mp4 media header (mdhd) v0 atoms are a minimum of 8 bytes for size & type information, plus 24 bytes for remaining entries (`24 +8`) bytes in total, rather than (`24 + 4`).
Relates to #895 (same issue, different branch)
See https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/QTFFChap2/qtff2.html#//apple_ref/doc/uid/TP40000939-CH204-25615

TagLib2: Minor fix for mp4 media header v0 minimum size check

---

taglib/mp4/mp4properties.cpp

Mp4 media header (mdhd) v0 atoms are a minimum of 8 bytes for size & type information, plus 24 bytes for remaining entries (`24 +8`) bytes in total, rather than (`24 + 4`).
See https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/QTFFChap2/qtff2.html#//apple_ref/doc/uid/TP40000939-CH204-25615

Minor fix for mp4 media header v0 minimum size check

---

taglib/mp4/mp4properties.cpp

When parsing mp4 media header version 1 (mdhd) atoms, the timescale (unit) is parsed as a `LongLong` (8 bytes), but instead should be a `UInt` (4 bytes). This results in an incorrect timescale, and also pushes the offset of the duration (length) off by 4 bytes.
The end result being that the AudioProperties track length for mp4's with mdhd v1 comes back as 0.
**Note**: This change is untested.
Relates to #891 & #892 
See: https://wiki.multimedia.cx/index.php/QuickTime_container
|  Entry | Bytes (v0) | Bytes (v1) |
| :---         |     :---:      | :---: |
| size  | 4  | 4 |
| type  | 4  | 4 |
| version | 1 | 1 |
| flags | 3 | 3 |
| creation time* | 4 | **8** |
| modification time* | 4 | **8** |
| time scale | 4 | 4 |
| duration* | 4 | **8** |
| language | 2 | 2 |
| quality | 2 | 2 |

Mp4 MediaHeader v1 parsing fix

---

CMakeLists.txt
taglib-config.cmake

Same as #690.
Otherwise, programs which are using `taglib-config` for pulling in taglibs dependency will detect the wrong libraries when cross-compiling.

fix taglib-config file for cross compiling

---

taglib/mpeg/id3v2/id3v2frame.cpp
taglib/mpeg/id3v2/id3v2framefactory.cpp
tests/test_id3v2.cpp

This adds support for the GRP1 Grouping frame, which is used by iTunes. It is done in the same way as for the WFED, MVNM and MVIN frames.

Support ID3v2 GRP1 frame introduced with iTunes 12.5.4.42, #903.

---

taglib/mp4/mp4tag.cpp

TagLib prior to #818 (commit ff28cf276c60)read and wrote the "rate" tag as
text, and switched to reading it as integer value even when the atom class
is a text type. This breaks reading existing files, and can be avoided by
taking the atom type into account.
This fixes issue #885.

Respect atom type when converting rate tag

---

taglib/toolkit/tfilestream.cpp

Closes https://github.com/taglib/taglib/issues/913.
The `fread(3C)` function potentially buffers the input stream and needs `fflush` following a `ftruncate(2)` being called; ie
```
FILE* f = fopen(...);
ftruncate(fileno(f), 10);
// fflush(f);  -- this is needed here
fseek(f, 10, SEEK_SET);  // seek to where we've truncated the file
fread(....);   // this will read data that has been truncated but buffered
```
These functions are used by code by `tfilestream` for some file operations, in particular the stripping of MP3 tags.
The missing `fflush` causes a problem with MP3 stripping of APE and ID3v1 tags - these tags reside at the end of the file and in this order if both exist.
Stripping functionality for `APE` tags `seek` to the end of the tag (based on `APELocation` and `APEOriginalSize`) …

tfilestream truncate/read bug - MP3 stripping fix

---

taglib/mp4/mp4tag.cpp

setTrack()/setYear() accepts 0 to remove the tag as per documentation/functionality across other tpyes (mp3/flac/...); m4a do not honour this and instead sets the underlying value to 0 instead of removing.
Fixes #911 
Regression test code:
```
#include <iostream>
#include <taglib/mp4file.h>
int main(int argc, char *argv[])
{
if (argc != 4) {
return 1;
}
try
{
TagLib::MP4::File  f(argv[1], false);
f.tag()->setYear(atoi(argv[2]));
f.tag()->setTrack(atoi(argv[3]));
f.save();
}
catch (const std::exception& ex)
{
std::cerr << ex.what() << std::endl;
}
return 0;
}
```
Run as:
```
a.out /tmp/foo.m4a 2019 5
a.out /tmp/foo.m4a 0 0
fffprobe -hide_banner -i /tmp/foo.m4a
```

MP4 - setTrack()/setYear() accepts 0 to remove the tag

---

taglib/CMakeLists.txt

Without this change, TagLib is unusable as part of CMake projects that rely on `add_subdirectory()` for dependencies, as it tries to add `<top-level source dir>/3rdparty` to its include directories, instead of `<taglib source dir>/3rdparty`.

Make TagLib seach in its source dir for utf8-cpp.

---

taglib-config.cmake

Commit d4c938cbc766ffb400c09efb9e696fce2537d81e is about fixing taglib-config for proper cross-compilation (#906). The fix is right in principle, but wrong in adding `CMAKE_SYSROOT`. The correct prefix path should be set outside of the config file as some embedded Linux distros like OpenWrt or OpenEmbedded install with a different DESTDIR, and dependent packages see a different sysroot.

Drop CMAKE_SYSROOT from taglib-config

---

taglib/ogg/opus/opusproperties.cpp
taglib/ogg/speex/speexproperties.cpp
taglib/ogg/vorbis/vorbisproperties.cpp
tests/test_ogg.cpp
tests/test_opus.cpp

This commit fixes #874 by subtracting the size of the XiphComment header data when calculating the bitrate for audio formats which use an Ogg container (Vorbis, Opus, Speex). The bitrate calculated is not as accurate as when decoding the whole stream (and then being able to subtract the whole overhead), but still accurate and fast enough. The reported bitrate will no longer be completely wrong when files contain large metadata, for example when embedding cover art.

Calculate Ogg bitrate without comment size (#874)

---

taglib/riff/rifffile.cpp

Currently padding in RIFF files is ignored if it is not zero. To allow parsing of files with non zero padding bytes, this patch changes the parsing of RIFF files in the following way:
* If a zero padding byte is found, it is accepted and handled as before.
* If the padding byte is not zero, it is accepted if the four bytes following the padding byte contain a valid chunk ID but the four bytes starting at the padding byte would not be a valid chunk ID, i.e. parsing would fail without this patch.
This should make parsing more tolerant in the presence of non zero padding bytes while still providing the feature that chunks at odd offsets can be parsed.

Do not ignore non zero RIFF padding if leading to parse error (#882)

---

taglib/mp4/mp4tag.cpp
taglib/mp4/mp4tag.h
tests/test_mp4.cpp

This will make the behavior for MP4 tags compliant to the API documentation and consistent with other tag formats.

MP4: Remove item when empty string is set (#929)

---

.travis.yml

Hi,
I had added ppc64le (Linux on Power) support on travis-ci in the branch and looks like its been successfully added. I believe it is ready for the final review and merge. The travis ci build logs can be verified from the link below.
https://travis-ci.com/github/ujjwalsh/taglib/builds/182294668
Please have a look.
Regards,
Ujjwal

Adding support for Linux on power

---

taglib/mpeg/mpegproperties.cpp

Do not ran away if we cannot find last frame, still export info we've got
Test file: https://yadi.sk/d/BXPDT2jB3SwrUg

fix reading audioproperties for broken mp3 files

---

taglib/fileref.cpp

Since the resolve only use the filename, there is no reason not to probe
them, as a filename might be available through the IOStream interface.
When using a ByteVectorStream, the filename will be empty and user
defined resolvers won't be probed.

fileref: Use user defined resolvers on streams

---

taglib-config.cmake

This matches the syntax of the 1.12 beta release and fixes issues where a user's libdir is not at ${exec_prefix}/lib but ${exec_prefix}/lib64 or otherwise.

taglib-config.cmake has static libdir and includedir variables

---

taglib/riff/rifffile.cpp
tests/test_aiff.cpp
tests/test_wav.cpp

This will allow editing the tags of WAV files which have data appended at the end. The corresponding unit test checks that the original contents are still available after editing the metadata of such files.

Accept WAV files with garbage appended (#973)

---

taglib/riff/wav/wavproperties.cpp
tests/test_wav.cpp

When a WAV file with float format without a `fact` chunk containing a `totalSamples` value is encountered, the bitrate is not calculated. However, since all samples have the same number of bits, the number of samples can be calculated from the size of the `data` chunk and number of channels and bits per sample, as it is done in the PCM case.

Calculate bitrate for IEEE Float WAV files without fact chunk (#959)

---

taglib/flac/flacfile.cpp
tests/test_flac.cpp

When the picture block is large and comes before the comment block, Windows will no longer display the tags. This can be fixed by storing the comment block before the picture block instead of appending it at the end.

FLAC: Store comment block before picture block (#954)

---

CMakeLists.txt
Doxyfile.cmake

The options WITH_ASF and WITH_MP4 where remove in commit dd846904cbc1ef3ee628d77f0c9df88ef8967816 back in 2011. It's time to remove the leftovers :-)

Drop leftovers WITH_ASF and WITH_MP4

---

taglib/ape/apetag.cpp
taglib/asf/asffile.cpp
taglib/flac/flacfile.cpp
taglib/mpc/mpcproperties.cpp
taglib/mpeg/id3v2/frames/ownershipframe.cpp
taglib/mpeg/id3v2/id3v2synchdata.cpp

While fuzzing another project I started getting notifications from KDE that `kdeinit5` was crashing trying to generate thumbnails for the invalid FLAC files that were being produced. That piqued my curiosity and so I made a rudimentary fuzzer for taglib which discovered the following issues.
`kdeinit5` doesn't appear to use taglib for all file types, so opening a folder containing the interesting inputs only produces the following crash logs as well as causing 1 core to pin at 100% inside taglib:
```
#4  0x00007f8b080959d5 in raise () from /lib64/libc.so.6
#5  0x00007f8b0807e8a4 in abort () from /lib64/libc.so.6
#6  0x00007f8ae8274bd8 in std::__replacement_assert(char const*, int, char const*, char const*) () from /lib64/libtag.so.1
#7  0x00007f8ae8280beb in …
```

Fuzzer fixes

---

taglib/toolkit/trefcounter.cpp

If you don't have `HAVE_GCC_ATOMIC` defined (for some reason) you'll get an error:
```
../../../libs/taglib/taglib-1.12/taglib/toolkit/trefcounter.cpp:55:21: error: duplicate ‘volatile’
55 | # define ATOMIC_INT volatile int
|                     ^~~~~~~~
../../../libs/taglib/taglib-1.12/taglib/toolkit/trefcounter.cpp:69:14: note: in expansion of macro ‘ATOMIC_INT’
69 |     volatile ATOMIC_INT refCount;
```

Fix "error: duplicate ‘volatile’" on systems without HAVE_GCC_ATOMIC in 1.12

---

taglib/fileref.cpp

This is the case for Opus files with an ogg extension.

Detect by contents if file detected by extension is invalid (#1011)

---

taglib/mp4/mp4atom.cpp
taglib/mp4/mp4atom.h
taglib/mpeg/id3v1/id3v1genres.cpp

Avoids using a non const global variable.
Signed-off-by: Rosen Penev <rosenp@gmail.com>

add missing const

---

taglib/mpeg/id3v2/id3v2framefactory.cpp
taglib/mpeg/id3v2/id3v2tag.cpp

Found with cppcoreguidelines-pro-type-static-cast-downcast
Signed-off-by: Rosen Penev <rosenp@gmail.com>

clang-tidy: replace static_cast with dynamic_cast

---

.gitignore

Other entries were copied from KDE/marble repo as well.
See also: https://invent.kde.org/sdk/kdesrc-build/-/issues/86

Add compile_commands.json to gitignore

---

CMakeLists.txt

Use CMAKE's `CMAKE_<LANG>_COMPILER_ID`, available from 3.0.2.
See: https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_ID.html

Add `-Wall` compiler flag to Clang compilers.

---

taglib/mp4/mp4file.cpp
taglib/mp4/mp4file.h
taglib/mp4/mp4tag.cpp
taglib/mp4/mp4tag.h
tests/test_mp4.cpp

Currently, MP4 tags can only grow. If items are removed, they are just replaced by padding in the form of "free" atoms. This change will remove the whole "meta" atom when an MP4 tag without items is saved. This will make it possible, to bring the file back to its pristine state without metadata.

Remove MP4 meta atom when empty tag is saved

---

taglib/ape/apetag.cpp
taglib/ogg/xiphcomment.cpp
taglib/toolkit/tmap.h
taglib/toolkit/tmap.tcc
taglib/toolkit/tpropertymap.cpp
taglib/toolkit/tpropertymap.h
tests/test_propertymap.cpp

Fixes #931 
``` 
TagLib::FLAC::File f(argv[1]);
f.xiphComment()->removeFields("TITLE");
std::cout << "FIRST (removed title)\n" << f.properties() << "\n";
f.save();
f.tag()->title();
```
Whilst `title()` returns empty string, the `Ogg::XiphComment` interface will create an empty entry in the `FieldListMap` for `TITLE`.  This is inconsistent with MP3/MP4 interfaces in the library.
This behaviour is seen for `TITLE`, `ARTIST`, `ALBUM`, `GENRE`, `COMMENTS`/`DESCRIPTION` which are fixed with this PR

FLAC - lookup on non existant tags do not inadvertently create entry in FieldListMap

---

taglib/tagutils.cpp
tests/test_apetag.cpp

This could cause incorrect tag parsing. Closes https://github.com/taglib/taglib/issues/1043.

Utils: Fix potential ID3v1 false positive in the presence of an APE tag.

---

taglib/asf/asftag.cpp
taglib/mpeg/id3v2/id3v2frame.cpp
tests/test_asf.cpp
tests/test_mpeg.cpp

Also use "WORK" for ASF "WM/ContentGroupDescription", as it corresponds to "TIT1" according to https://docs.microsoft.com/en-us/windows/win32/wmformat/id3-tag-support.
Add property "COMPILATION" for ID3v2 "TCMP" to be consistent with MP4 "cpil".
On request from https://mail.kde.org/pipermail/taglib-devel/2022-March/003025.html.

Use property "WORK" instead of "CONTENTGROUP" for ID3v2 "TIT1" frame

---

taglib/mpeg/id3v2/frames/chapterframe.cpp
taglib/mpeg/id3v2/frames/tableofcontentsframe.cpp
taglib/mpeg/id3v2/id3v2frame.h

There currently is no way to set the ID3v2 version of a frame's header using public API.
ID3v2 table of contents and chapter frames may contain other embedded frames. The [specification for these frames](https://id3.org/id3v2-chapters-1.0) is an addendum to both ID3v2.3 and ID3v2.4. While the spec doesn't explicitly state that the ID3 version of the embedded frames should match that of the containing frame, it seems to be a reasonable assumption. The examples given in the spec refer to sync-safe integers so presumably are intended to be examples for ID3v2.4 and not meant to be normative for both ID3 versions.
Currently when an ID3v2 tag is rendered the version of the `Frame::Header` (v2.3 or v2.4) is set in `ID3v2::Tag::render()` prior to calling the frame's `render` method. The frame has …

Fix ID3v2 version handling for embedded frames

---

taglib/mpeg/id3v2/frames/textidentificationframe.cpp
tests/test_id3v2.cpp

Some ID3v2.4.0 frames such as text information frames support multiple strings
separated by the termination code of the character encoding. If the encoding
is $01 UTF-16 with BOM, all strings shall have the same byte order. In the
multi strings written by TagLib, all string elements of such a multi string
have a BOM. However, I have often seen tags where a BOM exists only at the
beginning, i.e. at the start of the first string. In such a case, TagLib will
only return a list with the first string and a second empty string. This
commit will detect such cases and parse the strings without BOM according to
the BOM of the first string.

Correctly parse ID3v2.4.0 multiple strings with single BOM (#1055)

---

taglib/toolkit/tfilestream.cpp

Hi,
When playing around with my app I spotted that `hotspot` shows taglib's `FileStream::readBlock` spending a significant amount of time reading file length for what seems like prevention of over-allocating the buffer. Turns out that fseeking around the file on each read is not ideal, however, the mechanism is worth to keep around since allocating e.g. (uint32_t(0) - 1) bytes isn't ideal either.
Tested it based with taglib v1.12 as a shared lib that I had previously installed, on manjaro with 5.19.13-1 kernel with i5-4690k cpu and my playlist that consists of 1270 tracks:
```
208 flac
21 m4a
1007 mp3
34 wav
```
Some flamegraphs, highlighted parts are paths to `FileStream::length`.
Before:
After:
```shell
hyperfine --warmup 3 -r 30 --prepare 'rm ~/.config/foobar-debug/cache.db' './foobar' …
```

FileStream: seek only when length exceeds buffer size

---

CMakeLists.txt

https://raw.githubusercontent.com/microsoft/vcpkg/master/ports/taglib/msvc-disable-deprecated-warnings.patch from Uwe Klotz (uklotzde)

MSVC: Disable warnings for internal invocations of API functions (#1000)

---

taglib/toolkit/tmap.h
taglib/toolkit/tmap.tcc
taglib/toolkit/tpropertymap.cpp
taglib/toolkit/tpropertymap.h
taglib/toolkit/tstring.cpp
taglib/toolkit/tstring.h

Found with readability-const-return-type
Signed-off-by: Rosen Penev <rosenp@gmail.com>

clang: remove const return

---

taglib/mpeg/id3v2/id3v2framefactory.cpp
taglib/mpeg/id3v2/id3v2framefactory.h

This PR changes the ID3v2-FrameFactory so it is possible to subclass it for implementing own frames.
Additionally it splits up the createFrame() method to make its usage in subclasses a bit more easy.
As this is a binary-incompatible change I do not expect you to take this PR in consideration until next major release.

Improve FrameFactory subclassing merge

---

taglib/toolkit/trefcounter.cpp
taglib/toolkit/trefcounter.h

Since it appears the next version of TagLib will use C++17 features it's possible to simplify `RefCounter` using C++11 atomics.

Use C++11 atomics for RefCounter

---

tests/test_fileref.cpp
tests/utils.h

Found with google-readability-namespace-comments

clang-tidy: add ending namespace comments

---

taglib/toolkit/tiostream.cpp

Found with: modernize-use-equals-default

clang-tidy: use = default

---

taglib/fileref.cpp
taglib/toolkit/tdebuglistener.cpp
taglib/toolkit/tfilestream.cpp
taglib/toolkit/tiostream.cpp

Found with modernize-use-nullptr

clang-tidy: use nullptr

---

taglib/xm/xmfile.cpp

The former is standard C++ and the latter allows getting rid of autodelete.

std::list and unique_ptr conversions

---

taglib/ape/apeitem.h
taglib/asf/asfattribute.h
taglib/asf/asftag.h
taglib/flac/flacunknownmetadatablock.h
taglib/mod/modproperties.h
taglib/mp4/mp4item.h
taglib/mp4/mp4tag.h
taglib/mpeg/id3v2/frames/commentsframe.h
taglib/mpeg/id3v2/frames/generalencapsulatedobjectframe.h
taglib/mpeg/id3v2/frames/ownershipframe.h
taglib/mpeg/id3v2/frames/popularimeterframe.h
taglib/mpeg/id3v2/frames/privateframe.h
taglib/mpeg/id3v2/frames/synchronizedlyricsframe.h
taglib/mpeg/id3v2/frames/unsynchronizedlyricsframe.h
taglib/mpeg/id3v2/id3v2frame.h
taglib/riff/aiff/aifffile.h
taglib/riff/wav/wavfile.h
taglib/tag.h
taglib/toolkit/tbytevector.h
taglib/toolkit/tlist.h
taglib/toolkit/tstringlist.h
taglib/trueaudio/trueaudiofile.h
taglib/wavpack/wavpackfile.h

Found with readability-inconsistent-declaration-parameter-name

clang-tidy: fix mismatched variable names

---

taglib/toolkit/tdebuglistener.cpp
taglib/toolkit/tiostream.cpp

Found with readability-container-data-pointer

clang-tidy: use data()

---

taglib/fileref.cpp
taglib/flac/flacfile.cpp
taglib/ogg/xiphcomment.cpp

This was done in C++98 times. No longer needed with auto.

remove unused typedefs

---

taglib/ogg/oggfile.cpp

clang-tidy missed it as the declaration is outside of the loop.

convert missed for loop

---

CMakeLists.txt

Fix issue "CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.".

CMakeLists.txt cmake minimum version 3.5

---

taglib/mpeg/mpegfile.cpp
taglib/mpeg/mpegfile.h
tests/test_mpeg.cpp

This is based on the patch used by VLC, but the full scan is only skipped when the read style is explicitly set to Fast. https://code.videolan.org/videolan/vlc/-/blob/master/contrib/src/taglib/0001-Implement-ID3v2-readStyle-avoid-worst-case.patch

Do not scan full MPEG file for ID3v2 tag in Fast read style (#968)

---

taglib/toolkit/tmap.h
taglib/toolkit/tmap.tcc
tests/test_map.cpp

Adds C++11 braced list initialization to `Map`, same as for `std::map`. For example:
```C++
TagLib::Map<TagLib::String, int> m1 {
{"ONE", 1},
{"TWO", 2},
{"THREE", 3}
};
```
This can be useful for implementing a static lookup table.
Tests have been added for both construction and assignment.

Map: Support Braced List Initialization

---

taglib/toolkit/tlist.h
taglib/toolkit/tlist.tcc
tests/test_list.cpp

Adds C++11 braced list initialization to `List`, same as for `std::list`. For example:
```C++
TagLib::List<int> m1 {
1,
2,
3
};
```
- Tests have been added for construction and assignment, for both the regular and pointer specialization.
- For assignment, verified that the members are deleted when the list is of pointer type and auto delete is set to true

List: Support Braced List Initialization

---

taglib/toolkit/tbytevector.cpp
taglib/toolkit/tbytevector.h
tests/test_bytevector.cpp

I'm currently working on #1149. In Matroska, some elements have a UID which is implemented as a 64 bit unsigned integer. `ByteVector` currently does not have conversions for `ULongLong`, only `LongLong`. Casting an unsigned integer type to a signed integer type is implementation-defined if the value is higher than the max value of the signed type, so I would like to have a `ULongLong` function available to avoid the cast.
While looking at the code, I made some other improvements as well. Here is a summary of the changes:
- Added `ByteVector::toULongLong`, `ByteVector::fromULongLong`, and tests for both
- Added `ByteVector::fromUShort`, and tests
- Added tests for all existing integer-based `ByteVector::from*` functions. Currently, there are no tests for these functions
- Fixed a function …

Add ByteVector Conversion Functions, Tests

---

taglib/toolkit/tlist.h
taglib/toolkit/tlist.tcc
tests/test_list.cpp

I would like to be able to sort the objects contained in a `List`. We cannot use `std::sort()` on `List` because the iterators do not support random access. The underlying STL class `std::list` does have a sort function, however. This PR adds sort functions to `List` based on `std::list::sort()`. See the [Cppreference page](https://en.cppreference.com/w/cpp/container/list/sort) for more information.
The basic function without arguments will sort the `List` in ascending order. The class contained in `List` needs to support the `<` operator.
Additionally, there is an overload which takes a function object `Comp`. You can use this to provide custom sorting logic to the function. For example, a lambda based on some attribute of a class that can be accessed through a getter function:
```C++ …
```

List: Add Sort Functions

---

.github/workflows/build.yml
bindings/c/tag_c.cpp
bindings/c/tag_c.h
examples/tagreader_c.c
taglib/fileref.cpp
taglib/fileref.h
tests/CMakeLists.txt
tests/test_fileref.cpp
tests/test_tag_c.cpp

Provides a unified API for complex properties in the same way as the Properties API in the C bindings. Since constructing and traversing complex properties in C is a bit complicated, there are convenience functions for the most common use case of getting or setting a single picture.
TAGLIB_COMPLEX_PROPERTY_PICTURE(props, data, size, "Written by TagLib",
"image/jpeg", "Front Cover");
taglib_complex_property_set(file, "PICTURE", props);
and
TagLib_Complex_Property_Attribute*** properties =
taglib_complex_property_get(file, "PICTURE");
TagLib_Complex_Property_Picture_Data picture;
taglib_picture_from_complex_property(properties, &picture);

C bindings for complex properties like pictures (#953)

---

bindings/c/tag_c.cpp
bindings/c/tag_c.h
examples/tagreader.cpp
examples/tagreader_c.c
examples/tagwriter.cpp
taglib/fileref.cpp
taglib/fileref.h
taglib/tag.h
taglib/toolkit/tfile.h
taglib/toolkit/tstring.cpp
taglib/toolkit/tvariant.cpp
tests/test_complexproperties.cpp
tests/test_fileref.cpp
tests/test_sizes.cpp
tests/test_tag_c.cpp

Use `FileRef` for `TagLib_File` (C bindings), which allows to drop its deprecated `create()` method and delete duplicated code. It also allows to easily provide a feature to access files from memory with the C bindings (#987).
`FileRef` now has all the property methods, so that it is possible to do without its `file()` method, the use of which is discouraged in the documentation.
Noteworthy changes: `FileRef` is no longer virtual (the destructor was the only virtual method), and printing a `String` to `cout` will now use UTF-8 instead of ISO-8859-1 encoding.

Improve FileRef, C bindings to read file from memory (#987)

---

.github/workflows/build.yml
taglib/CMakeLists.txt

Revert "Fix build on Mac with Homebrew utf8cpp"
This reverts commit 70b4ce79fb493e45ae8884389ed146cf334a0369.
Is now fixed upstream
https://github.com/nemtrif/utfcpp/pull/113
https://github.com/nemtrif/utfcpp/releases/tag/v4.0.2 https://github.com/Homebrew/homebrew-core/pull/153333

GitHub Actions: Update Homebrew utfcpp to 4.0.2

---

taglib/mp4/mp4properties.cpp
tests/test_mp4.cpp

As reported in #1165, M4A files exists which have a duration of zero in the media header (mdhd). In such a case, the duration is now looked up in the video header (mvhd).

MP4: Get duration from mvhd if not present in mdhd (#1165)

---

taglib/CMakeLists.txt
taglib/mp4/mp4file.cpp
taglib/mp4/mp4file.h
taglib/mp4/mp4item.h
taglib/mp4/mp4itemfactory.cpp
taglib/mp4/mp4itemfactory.h
taglib/mp4/mp4tag.cpp
taglib/mp4/mp4tag.h
tests/test_mp4.cpp

Refactored the _mp4tag.cpp_ code to extract an `MP4::ItemFactory`, which lets the client add new atom types in the same way as with `ID3v2::FrameFactory` for ID3v2 tags.
A custom item factory adding support for a "tsti" integer atom and a "tstt" text atom can be implemented like this:
```
class CustomItemFactory : public MP4::ItemFactory {
protected:
NameHandlerMap nameHandlerMap() const override
{
return MP4::ItemFactory::nameHandlerMap()
.insert("tsti", ItemHandlerType::Int)
.insert("tstt", ItemHandlerType::Text);
}
};
```

Clients can control supported MP4 atoms using an ItemFactory

---

taglib/dsdiff/dsdifffile.cpp
taglib/dsf/dsffile.cpp
taglib/flac/flacfile.cpp
taglib/mpeg/id3v2/frames/textidentificationframe.cpp
taglib/mpeg/id3v2/frames/textidentificationframe.h
taglib/mpeg/id3v2/id3v2frame.cpp
taglib/mpeg/id3v2/id3v2frame.h
taglib/mpeg/id3v2/id3v2framefactory.cpp
taglib/mpeg/id3v2/id3v2framefactory.h
taglib/mpeg/id3v2/id3v2tag.cpp
taglib/mpeg/mpegfile.cpp
taglib/riff/aiff/aifffile.cpp
taglib/riff/aiff/aifffile.h
taglib/riff/wav/wavfile.cpp
taglib/tagunion.h
taglib/trueaudio/trueaudiofile.cpp
tests/CMakeLists.txt
tests/test_id3v2framefactory.cpp

Because the main extension point of FrameFactory was using a protected Frame subclass, it was not really possible to implement a custom frame factory. Existing Frame subclasses also show that access to the frame header might be needed when implementing a Frame subclass.

Fix extensibility of ID3v2 FrameFactory

---

taglib/toolkit/tlist.h
taglib/toolkit/tlist.tcc
taglib/toolkit/tmap.h
taglib/toolkit/tmap.tcc
tests/test_list.cpp

When calling `setAutoDelete()` on the implicitly shared copy of a list, also auto-deletion of the original container was modified because it was not detached. On the other hand, `detach()` was called by some methods getting an `Iterator` parameter, which can lead to modification of other implicitly shared copies but not the object is was called on. This happens when the method is called on a not-already-detached container, which is normally not the case because the container is detached when the iterator is taken (e.g. calling `begin()`). In such methods `detach()` cannot be called, and the client must make sure that the iterator is taken after making an implicit copy. This will **not** work:
List<int> l1 = { 1 };
auto it = l1.begin();
List<int> l2 = l1;
l1.erase(it);
This will modify …

Detach list when setAutoDelete() is called, do not detach with Iterator parameters

---

taglib/mp4/mp4file.cpp
tests/test_mp4.cpp

If an M4A file contains trailing garbage (e.g. an APE tag at the end of the file), it was considered invalid since [e21640b]. It is important to make sure that atoms which affect modifications written by TagLib are valid, otherwise the file might be damaged. However, in cases where invalid atoms do not affect modifications (which are only done inside the root level "moov" and "moof" containers), they can be safely ignored.
This commit allows trailing garbage in M4A files as it is also accepted in MP3, WAV and DSF files.

Tolerate trailing garbage in M4A files (#1186)

---

taglib/mod/modfilebase.cpp

Fix another implicit conversion I missed in the last PR

Fix implicit conversion

---

taglib/xm/xmfile.cpp

@ufleisch this may or may not be beneficial. I'm not sure how many XM files with sizes this large are floating around, but I don't think this fix alone will get TagLib working for them.

Use offset_t in XM::File::save()

---

taglib/CMakeLists.txt

It was only used for C files, thereby making symbols of internal classes like TagUnion visible.

Apply VISIBILITY_HIDDEN also to C++ files

---

taglib/fileref.cpp
taglib/flac/flacfile.cpp
taglib/flac/flacfile.h
taglib/mpeg/mpegfile.cpp
taglib/mpeg/mpegfile.h
taglib/trueaudio/trueaudiofile.cpp
taglib/trueaudio/trueaudiofile.h
tests/test_id3v2framefactory.cpp

Make constructors consistent so that the FrameFactory is at the end and optional. Mark the alternative constructors as deprecated.

Unify File constructors with ID3v2::FrameFactory parameter (#1196)

---

taglib/ape/apefooter.h
taglib/ape/apeitem.h
taglib/asf/asfattribute.h
taglib/asf/asfpicture.h
taglib/mp4/mp4coverart.h
taglib/mp4/mp4item.h
taglib/mpeg/id3v2/id3v2extendedheader.h
taglib/mpeg/id3v2/id3v2footer.h
taglib/mpeg/id3v2/id3v2frame.cpp
taglib/mpeg/id3v2/id3v2frame.h
taglib/mpeg/id3v2/id3v2header.h
taglib/mpeg/mpegheader.h
taglib/mpeg/xingheader.h
taglib/ogg/oggpage.h
taglib/ogg/oggpageheader.h
tests/test_sizes.cpp

Please have a look at these changes affecting the ABI of TagLib 2.0. Do you agree that these classes do not have to be virtual?

Make classes with destructor as only virtual member non-virtual 

---

examples/tagwriter.cpp

The -p option of tagwriter sample does not work.
This is because the picture file is open in text mode instead of binary. Also, the isFile function does not work on Windows in 32 bit mode with large files. Using _stat64 instead of stat solves the problem.

tagwriter option -p not working properly (#1236)

---

examples/framelist.cpp
examples/tagreader.cpp
examples/tagwriter.cpp

Although there are no particular problems with global scope in this example, it might cause issues in the future or when users try to copy-paste code from it directly.

Remove 'using namespace std' to avoid potential conflicts in tagreader.cpp example

---

taglib/CMakeLists.txt

This affects for example openSUSE Leap 15.6, which installs utfcpp 3.2.1 in its own folder.
Now not only utf8::cpp, but also utf8cpp is supported as a CMake target.

Support older utfcpp versions with utf8cpp CMake target (#1243)

---

taglib/flac/flacfile.cpp
taglib/ogg/flac/oggflacfile.cpp

The size of FLAC metadata blocks is stored in only 24 bits. Remove blocks exceeding this limit when saving FLAC and Ogg FLAC files.

Do not store too large FLAC metadata blocks (#1249)

---

taglib/mp4/mp4atom.h

You can't name parameter and structure field the same as complier frequently complain about this.

Fixed warning about shadowing variable

---

taglib/toolkit/tbytevector.cpp
taglib/toolkit/tutils.h

Most 64-bit Linux systems and macOS use LP64 with 64-bit `long` and pointers. Windows is slightly different and uses LLP64. 
This means that on LP64 systems `long` and `long long` are the same size.
As usual cppreference.com has a good page on [Fundamental Types](https://en.cppreference.com/w/cpp/language/types).
The current definition of the `byteSwap` functions use `unsigned short`, `unsigned int` and `unsigned long long` for 16-, 32-, and 64-bit uints.
The definitions I've seen for the various builtin `bswap` functions are defined using fixed with types.  For example [gcc](https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html) has the folllwing:
> Built-in Function: uint16_t __builtin_bswap16 (uint16_t x)
> Returns x with the order of the bytes reversed; for example, 0xaabb becomes …

Use fixed width types

---

CMakeLists.txt
INSTALL.md
config.h.cmake
tests/utils.h

The following user-settable values for CMake are supported:
- TESTS_DIR: Tests directory, is path to unit test data when 'data' is appended. Can be used to run the unit tests on a target.
- TESTS_TMPDIR: Directory for temporary files created during unit tests, system tmpdir is used if undefined. Has to be defined on systems without global temporary directory.

Support custom temp and tests directories (#1268)

---

taglib/mpeg/id3v2/frames/textidentificationframe.cpp
taglib/mpeg/id3v2/id3v2framefactory.cpp
tests/test_id3v2.cpp

The involvement/involvee pairs which are supported for TIPL properties (ARRANGER, ENGINEER, PRODUCER, DJ-MIX, MIX) are left in the TIPL frame, other pairs are moved to a TMCL frame. This will result in a consistent behavior for both ID3v2.3 and ID3v2.4 tags produced by MusicBrainz Picard.
This will improve compatibility of the property map interface with files tagged by MusicBrainz Picard. Two problems are addressed:
- The involvements supported by the property interface for TIPL frames (ARRANGER, ENGINEER, PRODUCER, DJ-MIX, MIX) are the keys which are used by MusicBrainz (arranger, engineer, producer, DJ-mix, mix), but different in case. Now the check is case insensitive, so that TIPL frames created by MusicBrainz will be accessible via the property interface.
- The IPLS frames from …

Convert IPLS to TIPL and TMCL (#1274)

---

bindings/c/tag_c.cpp
tests/test_tag_c.cpp

The C bindings would convert a char* to String using the default constructor, which uses the Latin1 encoding, breaking when a key contains a Unicode character (e.g. an ID3v2 comment description).
This was observed failing when trying to _read_ a .mp3 file (crashing using [similar code](https://github.com/turtletowerz/audiotags/blob/d044f29536ef11ad17613f98589488da2618341d/audiotags.c#L65) to the C binding test) mostly containing UTF-16 but also with the following comment frame, noting the BOM in the otherwise empty description:
```
00000000  43 4f 4d 4d 00 00 00 13  00 00 00 65 6e 67 ff fe  |COMM.......eng..|
00000010  00 78 79 7a 78 79 7a 78  79 7a 78 79 7a           |.xyzxyzxyzxyz|
```
This fix makes these values round-trip correctly between `taglib_property_keys` and …

Fix Unicode property keys in C bindings

---

taglib/toolkit/tvariant.h

taglib/toolkit/tvariant.h:43:29: note: candidate function
43 | TAGLIB_EXPORT std::ostream &operator<<(std::ostream &s, const TagLib::Variant &v);

Fix std::ostream not defined on Android NDK 29.0.14033849
