tests/test_ape.cpp

Separate the tests for fuzzed APE files.

---

taglib/mpeg/id3v2/frames/tableofcontentsframe.cpp

This is definitely duplicate with #464, but it looks like he won't return...

Fix a GCC/Clang warning about singed/unsigned comparison.

---

taglib/it/itproperties.cpp
taglib/it/itproperties.h
taglib/mod/modproperties.cpp
taglib/mod/modproperties.h
taglib/s3m/s3mproperties.cpp
taglib/s3m/s3mproperties.h
taglib/xm/xmproperties.cpp
taglib/xm/xmproperties.h

Add lengthInSeconds(), lengthInMilliseconds() properties. (always return 0)

(wishlist) MOD: AudioProperties improvements

---

tests/test_bytevector.cpp
tests/test_file.cpp
tests/test_id3v2.cpp
tests/test_info.cpp
tests/test_riff.cpp
tests/test_string.cpp

FreeBSD-8.2 (GCC 4.2.1) errors with uint ambiguity ...

Silence uint ambiguity errors in tests.

---

taglib/ape/apeitem.cpp
taglib/asf/asfattribute.cpp
taglib/mp4/mp4coverart.cpp
taglib/mp4/mp4item.cpp

Method 'operator=' should check its argument with 'this' pointer.

Add self-assignment check in operator=

---

taglib/flac/flacfile.cpp
taglib/flac/flacfile.h
tests/test_flac.cpp

This fixes all the issues reported at #622.

Fix saving FLAC files.

---

taglib/mp4/mp4file.cpp
taglib/mp4/mp4file.h
taglib/mp4/mp4tag.cpp
tests/test_mp4.cpp

This fixes the issue reported at #619.

Fix saving MP4 files.

---

taglib/mpeg/mpegfile.cpp
taglib/mpeg/mpegfile.h
tests/test_id3v2.cpp
tests/test_mpeg.cpp

This fixes all the issues reported at #618.

Fix saving MPEG files.

---

taglib/ape/apefile.cpp
taglib/ape/apefile.h
tests/test_ape.cpp

This fixes the issue reported at #624.

Fix saving APE files.

---

taglib/mpc/mpcfile.cpp
taglib/mpc/mpcfile.h
tests/test_mpc.cpp

This fixes the issue reported at #624.

Fix saving MPC files.

---

taglib/wavpack/wavpackfile.cpp
taglib/wavpack/wavpackfile.h
tests/test_wavpack.cpp

This fixes the issue reported at #624.

Fix saving WavPack files.

---

CMakeLists.txt
taglib.pc.cmake

.pc file use ${} as variables. so use @var@ as substitutions and set @ONLY parameter in CMakeLists.txt

Fix .pc file configuration.

---

bindings/c/tag_c.h

c: fix a typo

---

CMakeLists.txt

Added the missed option to build shared libraries from within the CMake GUI.
-Enjoy
fh  : )_~

Add BUILD_SHARED_LIBS option for CMake GUI.

---

taglib/ape/apetag.cpp
taglib/asf/asfattribute.h
taglib/mp4/mp4tag.cpp
taglib/mpeg/id3v2/frames/tableofcontentsframe.cpp
taglib/mpeg/id3v2/id3v2tag.cpp
taglib/toolkit/tstring.cpp
taglib/xm/xmfile.cpp

Made some small changes to slightly improve cppcheck analyser output.

Small improvements

---

taglib/mp4/mp4tag.cpp

Add support for the MP4 atoms cmID (Composer ID), purl (Podcast URL) and egid (Podcast GUID).

Add support for cmID, purl, egid MP4 atoms (#862).

---

bindings/c/tag_c.cpp
bindings/c/tag_c.h
examples/tagreader_c.c

expose `properties` via `C` bindings interface

C bindings - properties i/f

---

taglib/mpeg/id3v2/frames/tableofcontentsframe.cpp

Found with MSVC: warning C4456

small loop conversion:

---

taglib/it/itproperties.h
taglib/mod/modproperties.h
taglib/s3m/s3mproperties.h
taglib/toolkit/tfilestream.cpp
taglib/toolkit/tzlib.cpp
taglib/xm/xmproperties.h

-Wmicrosoft-unqualified-friend
-Wdllexport-explicit-instantiation-decl
-Wunused-parameter

fix Warnings under clang-cl

---

taglib/ape/apetag.cpp
taglib/mp4/mp4atom.cpp
taglib/mp4/mp4file.cpp
taglib/mpeg/id3v2/frames/textidentificationframe.cpp
taglib/mpeg/id3v2/id3v2frame.cpp
taglib/mpeg/id3v2/id3v2framefactory.cpp
taglib/ogg/xiphcomment.cpp
taglib/riff/riffutils.h
taglib/toolkit/tpropertymap.cpp
taglib/toolkit/tstring.cpp

Found with: readability-use-anyofallof

clang-tidy: convert to algorithms

---

taglib/toolkit/tpropertymap.cpp

clang-tidy: handle self assignment

---

taglib/riff/rifffile.cpp

move into vector

---

taglib/audioproperties.h
taglib/mpeg/id3v2/id3v2.h
taglib/mpeg/id3v2/id3v2framefactory.h
taglib/toolkit/taglib.h
taglib/toolkit/tfile.h
tests/test_it.cpp
tests/test_mod.cpp
tests/test_s3m.cpp
tests/test_xm.cpp

clang: fix documentation

---

taglib/ape/apetag.cpp
taglib/mp4/mp4atom.cpp
taglib/mp4/mp4file.cpp
taglib/mpeg/id3v2/frames/tableofcontentsframe.cpp
taglib/mpeg/id3v2/frames/textidentificationframe.cpp
taglib/mpeg/id3v2/id3v2frame.cpp
taglib/mpeg/id3v2/id3v2framefactory.cpp
taglib/ogg/xiphcomment.cpp
taglib/toolkit/tpropertymap.cpp

Also make sure that the lines calling std algorithms are not excessively long.

Restore const iterators replaced in #1107

---

taglib/toolkit/tbytevectorstream.cpp

Seems to have been an oversight at some point.

remove out of line declaration

---

taglib/tagunion.cpp

No need for vector. Allows simplifying some code.

replace vector with array

---

.github/dependabot.yml

Bot to update CI.
After this is merged, it will create a PR to update actions/checkout.

github: add dependabot

---

taglib/asf/asfattribute.cpp
taglib/asf/asfpicture.cpp
taglib/fileref.cpp
taglib/mp4/mp4coverart.cpp
taglib/mp4/mp4item.cpp
taglib/mpeg/mpegheader.cpp
taglib/toolkit/tiostream.cpp
taglib/toolkit/tlist.tcc
taglib/toolkit/tmap.tcc
taglib/toolkit/tstring.cpp
taglib/xm/xmfile.cpp

swap is not needed here as shared_ptr is copyable.

default some more

---

taglib/ogg/oggfile.cpp
taglib/riff/rifffile.cpp

change two loops to while

---

tests/test_string.cpp

Something about a deleted operator<<.

tests: fix compilation on MSYS2

---

taglib/toolkit/tfilestream.cpp

To make sure paths longer than MAX_PATH (260) can be opened, prefix local paths with `\\?\`, and UNC paths with `\\?\UNC\`.
I've tested on Windows 10 22H2 (Build 19045.3930), even when setting LongPathsEnabled to 1 in the registry, it still won't open files with long paths without prefixing them.
For more information see.: https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry

FileStream: Fix opening long paths on Windows

---

taglib/ape/apeproperties.cpp
taglib/asf/asfattribute.cpp
taglib/asf/asffile.cpp
taglib/asf/asfutils.h
taglib/dsdiff/dsdiffproperties.cpp
taglib/dsf/dsffile.cpp
taglib/dsf/dsfproperties.cpp
taglib/fileref.cpp
taglib/flac/flacfile.cpp
taglib/flac/flacproperties.cpp
taglib/it/itfile.cpp
taglib/mp4/mp4itemfactory.cpp
taglib/mp4/mp4properties.cpp
taglib/mpc/mpcproperties.cpp
taglib/mpeg/id3v1/id3v1tag.cpp
taglib/mpeg/mpegproperties.cpp
taglib/ogg/opus/opusproperties.cpp
taglib/ogg/speex/speexproperties.cpp
taglib/ogg/vorbis/vorbisproperties.cpp
taglib/shorten/shortenfile.cpp
taglib/shorten/shortenproperties.cpp
taglib/toolkit/tbytevector.cpp
taglib/trueaudio/trueaudioproperties.cpp
taglib/wavpack/wavpackproperties.cpp
tests/test_bytevector.cpp

There are a few warnings reported in the Ubuntu CI build. With theses changes, no warnings are reported in all CI builds.

Fix warnings
